# Generated by Django 3.2.5 on 2021-07-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', 'Cloths'), ('2', 'Vegitable'), ('3', 'Book')], max_length=100),
        ),
    ]
